// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "pairingToken": string;
      "workspaceWidth": number;
      "workspaceHeight": number;
      "workspaceLayout": string;
      "workspaceSidebarWidth": number;
      "apiKey": string;
      "baseUrl": string;
      "model": string;
      "maxTokens": number;
      "endpointsJson": string;
      "activeEndpointId": string;
      "mcpServersJson": string;
      "streamResponses": boolean;
      "memoryAutoExtract": boolean;
      "memoryConsent": string;
      "maxIterations": number;
      "maxToolCalls": number;
      "alwaysAllowedTools": string;
      "reasoningEffort": string;
      "contextWindowTokens": number;
      "uiFont": string;
      "uiFontSize": number;
      "pluginRuntimeHost": boolean;
      "codexExecutable": string;
      "kimiExecutable": string;
    };
  }
}
