// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "pairingToken": string;
      "workspaceWidth": number;
      "workspaceHeight": number;
      "apiKey": string;
      "baseUrl": string;
      "model": string;
      "maxTokens": number;
      "mcpServersJson": string;
      "streamResponses": boolean;
      "memoryAutoExtract": boolean;
      "alwaysAllowedTools": string;
    };
  }
}
