export {
  CONFUCIUS_EVENTS_PATH,
  CONFUCIUS_HEALTH_PATH,
  CONFUCIUS_HTTP_PREFIX,
  CONFUCIUS_LOOPBACK_ORIGIN,
  CONFUCIUS_MCP_PATH,
  CONFUCIUS_PROTOCOL_VERSION,
  CONFUCIUS_RPC_PATH,
  MCP_LATEST_PROTOCOL_VERSION,
  MCP_SUPPORTED_PROTOCOL_VERSIONS,
  buildHealthResponse,
  isConfuciusHealthResponse,
  negotiateMcpProtocolVersion,
} from "./http";
export type { ConfuciusHealthResponse } from "./http";

export { itemRefKey, parseItemRefKey } from "./item";
export type { CollectionRef, ItemRef } from "./item";

export type {
  ApprovalRequest,
  ApprovalKind,
  ApprovalResolution,
  ApprovalVerdict,
  PermissionMode,
  PermissionScope,
  ToolRiskLevel,
} from "./permissions";

export {
  LIBRARY_READ_TOOLS,
  LIBRARY_WRITE_TOOLS,
  MEMORY_READ_TOOLS,
  MEMORY_WRITE_TOOLS,
  PAPER_READ_TOOLS,
  PAPER_WRITE_TOOLS,
  mcpToolName,
} from "./tools";
export type {
  BuiltinToolName,
  JsonSchemaObject,
  LibraryReadTool,
  LibraryWriteTool,
  MemoryReadTool,
  MemoryWriteTool,
  PaperReadTool,
  PaperWriteTool,
  ToolCatalog,
  ToolConcurrency,
  ToolDefinition,
  ToolErrorCode,
  ToolFailure,
  ToolResult,
  ToolRuntimeMeta,
  ToolSuccess,
  ToolTransientMedia,
} from "./tools";

export type {
  ResearchTaskRecord,
  SessionContext,
  SessionMode,
  SessionRecord,
  TurnPhase,
  TurnRecord,
} from "./session";
export { isTaskStatus, migrateSessionRecord } from "./session";
export {
  MAX_TASK_TITLE_LENGTH,
  fallbackTaskTitle,
  isPlaceholderTaskTitle,
  isTaskTitleState,
  sanitizeGeneratedTaskTitle,
  temporaryTaskTitle,
} from "./taskTitle";
export type { TaskTitleState } from "./taskTitle";

export {
  AGENT_BACKENDS,
  ANNOTATION_TYPES,
  DEFAULT_ANNOTATION_COLORS,
  annotationsFromBody,
  artifactBodyMatchesKind,
  emptyLockedContext,
  isAgentBackendKind,
  isArtifactKind,
  isArtifactRecord,
  isCitation,
  isLockedContextSnapshot,
  isMemoryConsent,
  isRecoverableTurn,
  legacyContextSnapshot,
  lockedContextFingerprint,
  lockedContextSourceIds,
  mergeLockedContexts,
  summarizeArtifact,
  withLockedContextFingerprint,
} from "./research";
export {
  FEATURED_TASK_TEMPLATES,
  TASK_TEMPLATES,
  taskTemplate,
  templatesForContext,
  validateTemplateContext,
} from "./templates";
export type {
  TaskTemplate,
  TaskTemplateId,
  TemplateContextFailureReason,
  TemplateContextValidation,
} from "./templates";
export {
  MCP_TASK_GATEWAY_INSTRUCTIONS,
  artifactUpsertGuidance,
} from "./artifactPrompt";
export type {
  ArtifactPromptRef,
  ArtifactUpsertGuidanceInput,
} from "./artifactPrompt";
export type {
  AgentBackendKind,
  AnnotationDraft,
  AnnotationLegendEntry,
  AnnotationSetArtifactBody,
  AnnotationType,
  ArtifactBody,
  ArtifactKind,
  ArtifactRecord,
  ArtifactRevision,
  ArtifactStatus,
  ArtifactSummary,
  ArtifactUpsertInput,
  ArtifactWriteback,
  CapabilityProfile,
  Citation,
  CitationListArtifactBody,
  CollectionDiffArtifactBody,
  EvidenceAuditArtifactBody,
  LiteratureMapArtifactBody,
  ImageAnnotationDraft,
  LegacyHighlightDraft,
  LockedCollectionContext,
  LockedContextSnapshot,
  LockedItemContext,
  LockedReaderContext,
  LockedSavedSearchContext,
  LockedSelectionContext,
  MarkdownArtifactBody,
  MemoryConsent,
  MemoryProposal,
  RecoverableTurn,
  RuntimeStatus,
  TaskStatus,
  TaskAttachment,
  TaskAttachmentKind,
  TextAnnotationDraft,
  TriageTableArtifactBody,
} from "./research";

export type {
  ConfuciusEvent,
  ConfuciusEventBase,
  ConfuciusEventType,
  PlanStep,
} from "./events";
export {
  coalesceTimeline,
  nextReasoningFold,
  toolLineStatus,
  toolsSummary,
} from "./timeline";
export { escapeHtml, renderMarkdownHtml } from "./markdown";
export { buildOpenPdfUri, buildSelectUri, parseZoteroUri } from "./zoteroUri";
export type { ZoteroOpenPdfUri, ZoteroSelectUri, ZoteroUri } from "./zoteroUri";
export { countMindMapNodes, parseMindMapOutline } from "./mindmap";
export type { MindMapNode } from "./mindmap";
export type {
  ReasoningFold,
  TimelineBlock,
  TimelineToolCall,
} from "./timeline";

export { RPC_METHODS, validateConfigPatch } from "./rpc";
export {
  DEFAULT_MAX_ITERATIONS,
  DEFAULT_MAX_TOOL_CALLS,
  DEFAULT_UI_FONT,
  DEFAULT_UI_FONT_SIZE,
  DEFAULT_UI_LINE_HEIGHT,
  MAX_MAX_ITERATIONS,
  MAX_MAX_TOOL_CALLS,
  MAX_UI_FONT_SIZE,
  MIN_UI_FONT_SIZE,
  UI_FONTS,
  UI_LANGUAGES,
  UI_LINE_HEIGHTS,
  UI_LINE_HEIGHT_VALUES,
  clampMaxIterations,
  clampMaxToolCalls,
  clampUiFontSize,
  isReasoningEffort,
  isUiFont,
  isUiLanguage,
  isUiLineHeight,
  REASONING_EFFORTS,
} from "./rpc";
export {
  MAX_ENDPOINTS,
  activeEndpoint,
  applyEndpointPatch,
  blankEndpoint,
  defaultEndpoint,
  endpointIsConfigured,
  endpointLabel,
  newEndpointId,
  parseEndpointsJson,
  resolveEndpointStore,
} from "./endpoints";
export type {
  EndpointPatchResult,
  EndpointStore,
  LegacyModelPrefs,
  ModelEndpoint,
} from "./endpoints";
export type {
  ConfigListModelsParams,
  ConfigListModelsResult,
  ConfigSetParams,
  ConfigValidation,
  JsonRpcError,
  JsonRpcRequest,
  JsonRpcResponse,
  JsonRpcSuccess,
  LiveContextItem,
  LiveContextReader,
  LiveContextResult,
  LiveContextSelection,
  ContextSearchItem,
  ContextSearchItemsParams,
  ContextSearchItemsResult,
  MemoryDeleteParams,
  MemoryListParams,
  MemorySaveParams,
  MemorySearchParams,
  KnowledgeCreateParams,
  KnowledgeDeleteEntryParams,
  KnowledgeEntryKind,
  KnowledgeGetParams,
  KnowledgeListParams,
  KnowledgeSaveEntryParams,
  KnowledgeSearchParams,
  KnowledgeUpdateParams,
  LaunchConsumeResult,
  LaunchIntent,
  LogsListParams,
  LogsReadParams,
  LogsSearchParams,
  ModelConfigView,
  NoteProposeFromReplyParams,
  NoteProposeFromSessionParams,
  PromptContextOptions,
  ReaderOpenParams,
  ReasoningEffort,
  RpcMethod,
  SessionContextStats,
  SessionIdParams,
  SessionListResult,
  SessionNewParams,
  SessionPromptParams,
  SessionSetContextParams,
  SessionSetModeParams,
  SessionSetPermissionsParams,
  SessionEventsParams,
  SkillActivateParams,
  UiFont,
  UiLanguage,
  UiLineHeight,
  UpdateState,
  UpdateStatus,
  ArtifactGetParams,
  AttachmentPrepareParams,
  AttachmentPrepareResult,
  AttachmentReleaseParams,
  ArtifactListParams,
  ArtifactListResult,
  ArtifactUpsertParams,
  ArtifactWritebackParams,
  MemoryProposalListResult,
  MemoryProposalResolveParams,
  RuntimeConfigureParams,
  RuntimeSetPluginHostParams,
  RuntimeListResult,
  TaskListResult,
  TaskBranchParams,
  TaskNewParams,
  TaskPromptParams,
  TaskPreviewCapabilitiesParams,
  TaskPreviewCapabilitiesResult,
  TaskSetBackendParams,
  TaskSetContextParams,
  TaskStageTemplateParams,
} from "./rpc";
