#!/usr/bin/env node
// Generate apps/zotero-addon/src/modules/skills/builtin.ts from skills/*/SKILL.md.
// The skills directory is the source of truth; the addon bundles the generated
// module. Run with --check to fail (exit 1) when the file is out of sync.
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const skillsDir = join(root, "skills");
const target = join(
  root,
  "apps",
  "zotero-addon",
  "src",
  "modules",
  "skills",
  "builtin.ts",
);

if (!existsSync(skillsDir)) {
  console.error(`skills directory not found: ${skillsDir}`);
  process.exit(1);
}

const entries = readdirSync(skillsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const lines = [
  "// Generated by scripts/sync-skills.mjs from skills/*/SKILL.md — do not edit.",
  "// Run `npm run sync-skills` after changing a skill.",
  "",
  "export const BUILTIN_SKILLS: Record<string, string> = {",
];
for (const slug of entries) {
  const path = join(skillsDir, slug, "SKILL.md");
  if (!existsSync(path)) {
    continue;
  }
  const markdown = readFileSync(path, "utf8");
  lines.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(markdown)},`);
}
lines.push("};");
lines.push("");
const generated = lines.join("\n");

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== generated) {
    console.error(
      "builtin.ts is out of sync with skills/. Run `npm run sync-skills`.",
    );
    process.exit(1);
  }
  console.log("builtin.ts is in sync with skills/.");
  process.exit(0);
}

writeFileSync(target, generated, "utf8");
console.log(`Wrote ${target} from ${entries.length} skills.`);
